<?php


namespace Tests;

use HuanL\Core\Tests\HuanLHttpTest;
use HuanL\Extend\InsideHttpRequest;

class IndexTest extends HuanLHttpTest {

    public function setUp()/* The :void return type declaration that should be here would cause a BC issue */ {
        $this->dir= realpath('../');
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testModel() {
        $ret = $this->get('/model')->request()->json();
        $this->assertEquals($ret['code'], -1);
        $this->assertEquals($ret['msg'], '用户名不能为空');
    }

    public function testModel2() {
        $ret = $this->get('/model', ['user' => 'haha'])->request()->json();
        $this->assertEquals($ret['code'], -1);
        $this->assertEquals($ret['msg'], '密码不能为空');
    }

}